# Generated by Django 4.0.6 on 2023-10-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('introduction', models.CharField(max_length=100)),
                ('age', models.FloatField()),
                ('study', models.CharField(max_length=255)),
                ('degree', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Ph.D.', 'Ph.D.')], max_length=10)),
                ('experience', models.FloatField()),
                ('photo', models.ImageField(upload_to='photos/')),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
