# Generated by Django 4.0.6 on 2023-10-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='applicant',
            name='lname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
