# Generated by Django 4.0.6 on 2023-10-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_rename_name_applicant_fname_applicant_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='degree',
            field=models.CharField(choices=[('Undergradute', 'Undergradute'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Ph.D.', 'Ph.D.')], max_length=20),
        ),
    ]
