# Generated by Django 4.0.6 on 2023-11-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_alter_applicant_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
