# Generated by Django 4.0.6 on 2023-11-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_applicant_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='city',
            field=models.CharField(choices=[('city', 'city'), ('Baghdad', 'Baghdad'), ('Mosul', 'Mosul'), ('Al Başrah', 'Al Başrah'), ('Kirkuk', 'Kirkuk'), ('As Sulaymānīyah', 'As Sulaymānīyah'), ('Ar Ramādī', 'Ar Ramādī'), ('Erbil', 'Erbil'), ('An Najaf', 'An Najaf'), ('Karbalā’', 'Karbalā’'), ('An Nāşirīyah', 'An Nāşirīyah'), ('Al Ḩillah', 'Al Ḩillah'), ('Al ‘Amārah', 'Al ‘Amārah'), ('Ba‘qūbah', 'Ba‘qūbah'), ('Ad Dīwānīyah', 'Ad Dīwānīyah'), ('Az Zubayr', 'Az Zubayr'), ('Dahūk', 'Dahūk'), ('Al Fallūjah', 'Al Fallūjah'), ('Al Kūt', 'Al Kūt'), ('Ash Shāmīyah', 'Ash Shāmīyah'), ('Al Qurnah', 'Al Qurnah'), ('Al Ḩamzah', 'Al Ḩamzah'), ('Rāniyah', 'Rāniyah'), ('Sab‘ al Būr', 'Sab‘ al Būr'), ('Ash Shaţrah', 'Ash Shaţrah'), ('Kalār', 'Kalār'), ('Abī al Khaşīb', 'Abī al Khaşīb'), ('Zākhū', 'Zākhū'), ('As Samāwah', 'As Samāwah'), ('‘Aqrah', '‘Aqrah'), ('At Tājī', 'At Tājī'), ('Abū Ghurayb', 'Abū Ghurayb'), ('Khānaqīn', 'Khānaqīn'), ('Al Kūfah', 'Al Kūfah'), ('Sāmarrā’', 'Sāmarrā’'), ('Al Miqdādīyah', 'Al Miqdādīyah'), ('Nāḩiyat Ghammās', 'Nāḩiyat Ghammās'), ('Nāḩiyat Khān Banī Sa‘d', 'Nāḩiyat Khān Banī Sa‘d'), ('Sawrān', 'Sawrān'), ('Ţūz Khūrmātū', 'Ţūz Khūrmātū'), ('Salmān Bāk', 'Salmān Bāk'), ('Qal‘at Sukkar', 'Qal‘at Sukkar'), ('Umm Qaşr', 'Umm Qaşr'), ('Tikrīt', 'Tikrīt'), ('Al Fāw', 'Al Fāw'), ('Nāḩiyat al Iskandarīyah', 'Nāḩiyat al Iskandarīyah'), ('Aţ Ţārmīyah', 'Aţ Ţārmīyah')], default='Unknown', max_length=100),
        ),
    ]
